/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as FilesRouteImport } from './routes/files'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VirtualFlipperRouteImport } from './routes/virtual-flipper'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualFlipperRoute = VirtualFlipperRouteImport.update({
  id: '/virtual-flipper',
  path: '/virtual-flipper',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/device': typeof DeviceRoute
  '/files': typeof FilesRoute
  '/geo': typeof GeoRoute
  '/settings': typeof SettingsRoute
  '/virtual-flipper': typeof VirtualFlipperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/device': typeof DeviceRoute
  '/files': typeof FilesRoute
  '/geo': typeof GeoRoute
  '/settings': typeof SettingsRoute
  '/virtual-flipper': typeof VirtualFlipperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/device': typeof DeviceRoute
  '/files': typeof FilesRoute
  '/geo': typeof GeoRoute
  '/settings': typeof SettingsRoute
  '/virtual-flipper': typeof VirtualFlipperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/device'
    | '/files'
    | '/geo'
    | '/settings'
    | '/virtual-flipper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/device'
    | '/files'
    | '/geo'
    | '/settings'
    | '/virtual-flipper'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/device'
    | '/files'
    | '/geo'
    | '/settings'
    | '/virtual-flipper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DeviceRoute: typeof DeviceRoute
  FilesRoute: typeof FilesRoute
  GeoRoute: typeof GeoRoute
  SettingsRoute: typeof SettingsRoute
  VirtualFlipperRoute: typeof VirtualFlipperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-flipper': {
      id: '/virtual-flipper'
      path: '/virtual-flipper'
      fullPath: '/virtual-flipper'
      preLoaderRoute: typeof VirtualFlipperRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DeviceRoute: DeviceRoute,
  FilesRoute: FilesRoute,
  GeoRoute: GeoRoute,
  SettingsRoute: SettingsRoute,
  VirtualFlipperRoute: VirtualFlipperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
